# Generated by Django 5.0.3 on 2024-03-28 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('foto', models.ImageField(upload_to='usuario/')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('racha', models.JSONField(default={'Domingo': False, 'Jueves': False, 'Lunes': False, 'Martes': False, 'Miercoles': False, 'Sábado': False, 'Viernes': False})),
                ('estado', models.BooleanField(default=False)),
                ('registro', models.DateField(auto_now_add=True)),
                ('administrador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FotoPredeterminada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='predeterminado/')),
                ('registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lenguaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='lenguaje/')),
                ('urlDocumentation', models.URLField(max_length=2083)),
                ('colorHexadecimal', models.CharField(max_length=7)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('estado', models.BooleanField(default=False)),
                ('registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('explanation', models.TextField()),
                ('totalPreguntas', models.PositiveIntegerField(default=0)),
                ('estado', models.BooleanField(default=False)),
                ('registro', models.DateField(auto_now_add=True)),
                ('lenguaje', models.ForeignKey(limit_choices_to={'estado': True}, on_delete=django.db.models.deletion.CASCADE, to='api.lenguaje')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('pregunta', models.TextField()),
                ('respuesta', models.JSONField()),
                ('estado', models.BooleanField(default=False)),
                ('registro', models.DateField(auto_now_add=True)),
                ('nivel', models.ForeignKey(limit_choices_to={'estado': True}, on_delete=django.db.models.deletion.CASCADE, to='api.nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresoLenguaje', models.FloatField(default=0)),
                ('puntos', models.PositiveIntegerField(default=0)),
                ('nivelesPermitidos', models.JSONField()),
                ('registro', models.DateTimeField(auto_now=True)),
                ('lenguaje', models.ForeignKey(limit_choices_to={'estado': True}, on_delete=django.db.models.deletion.CASCADE, to='api.lenguaje')),
                ('usuario', models.ForeignKey(limit_choices_to={'estado': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
